// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqSignUp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignUp) Reset()         { *m = ReqSignUp{} }
func (m *ReqSignUp) String() string { return proto.CompactTextString(m) }
func (*ReqSignUp) ProtoMessage()    {}
func (*ReqSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ReqSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignUp.Unmarshal(m, b)
}
func (m *ReqSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignUp.Marshal(b, m, deterministic)
}
func (m *ReqSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignUp.Merge(m, src)
}
func (m *ReqSignUp) XXX_Size() int {
	return xxx_messageInfo_ReqSignUp.Size(m)
}
func (m *ReqSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignUp proto.InternalMessageInfo

func (m *ReqSignUp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqSignUp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResSignUp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResSignUp) Reset()         { *m = ResSignUp{} }
func (m *ResSignUp) String() string { return proto.CompactTextString(m) }
func (*ResSignUp) ProtoMessage()    {}
func (*ResSignUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ResSignUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResSignUp.Unmarshal(m, b)
}
func (m *ResSignUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResSignUp.Marshal(b, m, deterministic)
}
func (m *ResSignUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResSignUp.Merge(m, src)
}
func (m *ResSignUp) XXX_Size() int {
	return xxx_messageInfo_ResSignUp.Size(m)
}
func (m *ResSignUp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResSignUp.DiscardUnknown(m)
}

var xxx_messageInfo_ResSignUp proto.InternalMessageInfo

func (m *ResSignUp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResSignUp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSignUp)(nil), "proto.ReqSignUp")
	proto.RegisterType((*ResSignUp)(nil), "proto.ResSignUp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xce, 0x5c, 0x9c, 0x41, 0xa9,
	0x85, 0xc1, 0x99, 0xe9, 0x79, 0xa1, 0x05, 0x42, 0x52, 0x5c, 0x1c, 0x20, 0x15, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0xae, 0x20, 0xb1, 0xb8, 0xb8,
	0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x2b, 0x59, 0x82, 0x0c, 0x29, 0x86, 0x1a,
	0x22, 0xc4, 0xc5, 0x92, 0x9c, 0x9f, 0x02, 0x31, 0x80, 0x35, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62,
	0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x85, 0xea, 0x85, 0x71, 0x8d, 0x6c, 0xb9, 0xb8, 0x41,
	0x56, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xe9, 0x71, 0xb1, 0x41, 0x8d, 0x11, 0x80,
	0xb8, 0x53, 0x0f, 0xee, 0x3a, 0x29, 0x84, 0x08, 0xd4, 0x2a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x90,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x77, 0x65, 0xa4, 0x50, 0xda, 0x00, 0x00, 0x00,
}
